// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("API.Entities.AppReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Reason");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            DateTime = new DateTime(2021, 5, 24, 5, 33, 26, 559, DateTimeKind.Local).AddTicks(1794),
                            ReasonDescription = "Having a better commute will really help with my gas costs and ware and tear on my car.",
                            ReasonTitle = "Easy Commute",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 2,
                            DateTime = new DateTime(2021, 5, 24, 5, 33, 26, 559, DateTimeKind.Local).AddTicks(2902),
                            ReasonDescription = "Working with a good stable company will be a nice change from the companies and contracts I've been envolved with in the past",
                            ReasonTitle = "Stable company",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = 4,
                            DateTime = new DateTime(2021, 5, 24, 5, 33, 26, 559, DateTimeKind.Local).AddTicks(2912),
                            ReasonDescription = "The older I get the more important benifits matter to me.",
                            ReasonTitle = "Good Benifits",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Robbert",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Robert_Smith_%28musician%29_crop.jpg/1200px-Robert_Smith_%28musician%29_crop.jpg",
                            JoinDate = new DateTime(2019, 5, 24, 5, 33, 26, 556, DateTimeKind.Local).AddTicks(2985),
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Sally",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Sally_Field_%2811205%29_%28cropped%29.jpg/1200px-Sally_Field_%2811205%29_%28cropped%29.jpg",
                            JoinDate = new DateTime(2020, 5, 24, 5, 33, 26, 558, DateTimeKind.Local).AddTicks(961),
                            LastName = "Field"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Peter",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Peter_Gabriel_%283%29_%28cropped%29.jpg/1200px-Peter_Gabriel_%283%29_%28cropped%29.jpg",
                            JoinDate = new DateTime(2021, 3, 24, 5, 33, 26, 558, DateTimeKind.Local).AddTicks(984),
                            LastName = "Gaberial"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Genny",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e7/Ginny_Weasley_poster.jpg",
                            JoinDate = new DateTime(2020, 2, 24, 5, 33, 26, 558, DateTimeKind.Local).AddTicks(989),
                            LastName = "Weasley"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
